language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - Rcpp

script:
  - autoconf
  - R CMD build .
  - R CMD check *.tar.gzm --as-cran --no-manual